#Application url
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser config
browser=chrome

#credentials
username=Admin
password=admin123

#Implicitwait(in seconds)
implicitwait=10

#Explicit wait
explicitwait=20